[sdl]
fullscreen       = true
windowresolution = 1280x960
output           = texture

[render]
aspect           = true

[dosbox]
memsize          = 32

[cpu]
core             = auto
cputype          = pentium
cpu_cycles       = 60000

[gus]
gus              = true
gusbase          = 240
gusirq           = 5
gusdma           = 3

[sblaster]
sbtype           = sb16
sbbase           = 220
irq              = 7
dma              = 1
hdma             = 5
sbmixer          = true
oplmode          = auto

[capture]
capture_dir      = capture

[autoexec]
@echo off
mount c .
c:
copy assets\models\*.cob . >nul
copy assets\paths\*.pth . >nul
copy assets\worlds\*.wld . >nul
copy assets\luts\*.lut . >nul
copy assets\audio\*.* . >nul
copy assets\palettes\*.* . >nul
copy assets\data\*.* . >nul
TSFS.EXE
del *.cob >nul
del *.pth >nul
del *.wld >nul
del *.lut >nul
del *.xm >nul
del *.wav >nul
del *.raw >nul
del *.dat >nul
