[sdl]
fullscreen       = false
fulldouble       = false
windowresolution = 1280x960
output           = texture
autolock         = true

[render]
aspect           = true
scaler           = normal2x

[dosbox]
memsize          = 32

[cpu]
core             = auto
cputype          = pentium
cycles           = auto
cpu_cycles       = 60000

[gus]
gus              = true
gusbase          = 240
gusirq           = 5
gusdma           = 3

[sblaster]
sbtype           = sb16
sbbase           = 220
irq              = 7
dma              = 1
hdma             = 5
sbmixer          = true
oplmode          = auto

[capture]
capture_dir      = capture

[autoexec]
@echo off
mount c .
c:
TSFS.EXE
exit
